development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:7d823a45b771f4e9242a89b2efb50428@hammerjaw.redistogo.com:11666/
  channel_prefix: instatalk_production
